[build]
  command = "npm run build"
  publish = "dist" # Or "build", depending on your frontend (Vite = dist)
  functions = "backend" # Tells Netlify your server files are in the backend folder

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/api/:splat" # 'server' matches your server.js filename
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200