import express from 'express';
import mongoose from 'mongoose';
import { GoogleGenAI } from '@google/genai';
import User from '../models/User.js';
import ActionLog from '../models/ActionLog.js';

const router = express.Router();

// Helper to check for valid Mongo Object ID
const isValidObjectId = (id) => mongoose.Types.ObjectId.isValid(id);

/**
 * @route   POST /api/users
 * @desc    Find or create a user by username
 * @access  Public
 */
router.post('/users', async (req, res) => {
  try {
    const { username } = req.body;
    
    if (!username) {
      return res.status(400).json({ error: 'Username is required' });
    }

    let user = await User.findOne({ username });
    
    if (!user) {
      user = new User({ username });
      await user.save();
      return res.status(201).json(user);
    }

    return res.status(200).json(user);
  } catch (error) {
    console.error(`[User API Error] ${error.message}`);
    return res.status(500).json({ error: 'Failed to find or create user profile' });
  }
});

/**
 * @route   POST /api/log-action
 * @desc    Submit raw action text, parse with Gemini API, update User score and save ActionLog
 * @access  Public
 */
router.post('/log-action', async (req, res) => {
  try {
    const { userId, rawInput } = req.body;

    // 1. Validation
    if (!userId || !rawInput) {
      return res.status(400).json({ error: 'Both userId and rawInput are required parameters' });
    }

    if (!isValidObjectId(userId)) {
      return res.status(400).json({ error: 'Invalid userId format' });
    }

    // 2. Locate User
    const user = await User.findById(userId);
    if (!user) {
      return res.status(404).json({ error: 'User profile not found' });
    }

    // 3. Initialize Gemini SDK
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey || apiKey === 'your_gemini_api_key_here') {
      return res.status(500).json({ error: 'Gemini API key is not configured on the server' });
    }

    const ai = new GoogleGenAI({ apiKey });

    // 4. Query Gemini with structured output constraints
    const systemPrompt = `You are a carbon footprint and environmental analyst. Your task is to review the user's daily activity input and estimate its ecological impact.
Rules:
1. Provide a short 3-5 word summary in 'actionSummary' (e.g. 'Ate plant-based burger', 'Commuted in diesel SUV', 'Unplugged vampire electronics').
2. Estimate the carbon emissions in kg and return it in 'estimatedCo2Kg'. Active travel, plant-based diets, and low power usage are near 0. Single flights or long gas drives are double/triple digits.
3. Compute the 'scoreImpact' integer strictly bounded between -15 (extremely bad, e.g. buying coal power or a long-distance flight) and +15 (extremely green, e.g. switching home to solar energy or planting trees).`;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: `User logged activity: "${rawInput}"`,
      config: {
        systemInstruction: systemPrompt,
        responseMimeType: 'application/json',
        responseSchema: {
          type: 'OBJECT',
          properties: {
            actionSummary: {
              type: 'STRING',
              description: 'A 3-5 word description of the logged action.'
            },
            estimatedCo2Kg: {
              type: 'NUMBER',
              description: 'Estimated emissions generated by this action in kilograms.'
            },
            scoreImpact: {
              type: 'INTEGER',
              description: 'The net environmental score impact, bounded between -15 and +15.'
            }
          },
          required: ['actionSummary', 'estimatedCo2Kg', 'scoreImpact']
        }
      }
    });

    // 5. Parse Gemini's JSON response
    let parsedResult;
    try {
      const text = response.text;
      parsedResult = JSON.parse(text);
    } catch (parseError) {
      console.error(`[Gemini Parse Error] Failed parsing model text: ${response.text}`, parseError);
      return res.status(500).json({ error: 'AI engine returned invalid structured metrics' });
    }

    const { actionSummary, estimatedCo2Kg, scoreImpact } = parsedResult;

    if (actionSummary === undefined || estimatedCo2Kg === undefined || scoreImpact === undefined) {
      return res.status(500).json({ error: 'AI engine response was missing required fields' });
    }

    // 6. Update User's Profile
    // Accumulate total emissions
    user.totalCo2EmittedKg = Math.max(0, user.totalCo2EmittedKg + estimatedCo2Kg);
    // Adjust world health score, clamped between 0 and 100
    user.worldHealthScore = Math.max(0, Math.min(100, user.worldHealthScore + scoreImpact));

    await user.save();

    // 7. Save ActionLog
    const actionLog = new ActionLog({
      userId: user._id,
      rawInput,
      actionSummary,
      estimatedCo2Kg,
      scoreImpact
    });

    await actionLog.save();

    // 8. Return Response
    return res.status(200).json({
      success: true,
      user: {
        id: user._id,
        username: user.username,
        worldHealthScore: user.worldHealthScore,
        totalCo2EmittedKg: user.totalCo2EmittedKg
      },
      actionLog: {
        id: actionLog._id,
        rawInput: actionLog.rawInput,
        actionSummary: actionLog.actionSummary,
        estimatedCo2Kg: actionLog.estimatedCo2Kg,
        scoreImpact: actionLog.scoreImpact,
        loggedAt: actionLog.loggedAt
      }
    });

  } catch (error) {
    console.error(`[API Log Action Error] ${error.stack || error.message}`);
    return res.status(500).json({ error: error.message || 'Internal server error while logging action' });
  }
});

export default router;
